baseurl: "https://yo3nglau.github.io/blogs/"
title: "yo3nglau academic website"
googleAnalytics: ""
disqusShortname: ""
footnotereturnlinkcontents: "↩"
publishDir: "docs"
enableEmoji: true

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

languages:
  en:
    languageName: English
    languageCode: en-us
    weight: 1
  zh:
    languageName: 中文
    languageCode: zh-cn
    weight: 2
    menu:
      main:
        - name: 首页
          url: ""
          weight: 1
        - name: 分类
          url: "categories/"
          weight: 2
        - name: 标签
          url: "tags/"
          weight: 3

permalinks:
  # post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Categories
      url: "categories/"
      weight: 2
    - name: Tags
      url: "tags/"
      weight: 3

params:
  description: "With template [XMin](https://github.com/yihui/hugo-xmin) written by [Yihui Xie](https://yihui.org/) empowered by Hugo and blogdown."
  footer: "&copy; [yo3nglau](https://github.com/yo3nglau) {Year} | [Hugo](https://gohugo.io/) | [XMin](https://github.com/yihui/hugo-xmin)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - ["$$", "$$"]
          inline:
            - ["$", "$"]
